language: cpp
compiler: gcc
sudo: require
dist: trusty
services:
  - docker

script:
  - docker run --cap-add SYS_ADMIN --device /dev/fuse:mrw -v "$(readlink -f .):/ws" --rm -it ubuntu:16.04 bash -c "cd /ws; bash travis/travis-build.sh"

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh APPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
